# Generated by Django 5.1.6 on 2025-02-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clothing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("S", "Small"),
                            ("M", "Medium"),
                            ("L", "Large"),
                            ("XL", "Extra Large"),
                        ],
                        default="M",
                        max_length=20,
                    ),
                ),
                (
                    "colour",
                    models.CharField(
                        choices=[
                            ("Red", "Red"),
                            ("Blue", "Blue"),
                            ("Green", "Green"),
                            ("Black", "Black"),
                        ],
                        default="Red",
                        max_length=10,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("image", models.ImageField(upload_to="product_img/")),
            ],
        ),
        migrations.DeleteModel(
            name="Clothing",
        ),
    ]
